USE DATABASE_UCB

CREATE TABLE ARMA(	
	ID INT NOT NULL PRIMARY KEY, 
	DANHO INT NOT NULL,
	TAMANHO VARCHAR(20) NOT NULL,
	ALCANCE VARCHAR(20) NOT NULL,
	CARGADOR_BALAS INT NOT NULL,
	MIRA BIT NOT NULL
)

INSERT INTO ARMA VALUES (1, 50, 'Medio', 'Largo', 10, 0);
INSERT INTO ARMA VALUES (2, 40, 'Pequenho', 'Corto', 30, 0);
INSERT INTO ARMA VALUES (3, 45, 'Mediano', 'Medio', 40, 1);
INSERT INTO ARMA VALUES (4, 100, 'Grande', 'Largo', 5, 1);

CREATE TABLE PISTOLA(	
	ID INT NOT NULL PRIMARY KEY, 
	MODELO_PISTOLA VARCHAR(50) NOT NULL,
	ID_ARMA INT NOT NULL,
	FOREIGN KEY (ID_ARMA) REFERENCES ARMA(ID)
)

INSERT INTO PISTOLA VALUES (1, 'Magnum', 1);
INSERT INTO PISTOLA VALUES (2, 'T-95', 2);

CREATE TABLE METRALLETA(	
	ID INT NOT NULL PRIMARY KEY, 
	MODELO_METRALLETA VARCHAR(50) NOT NULL,
	ID_ARMA INT NOT NULL,
	FOREIGN KEY (ID_ARMA) REFERENCES ARMA(ID)
)

INSERT INTO METRALLETA VALUES (1, 'Scar', 1);
INSERT INTO METRALLETA VALUES (2, 'M-16', 3);
INSERT INTO METRALLETA VALUES (3, 'AK-47', 1);


CREATE TABLE SNIPER(	
	ID INT NOT NULL PRIMARY KEY, 
	MODELO_SNIPER VARCHAR(50) NOT NULL,
	ID_ARMA INT NOT NULL,
	FOREIGN KEY (ID_ARMA) REFERENCES ARMA(ID)
)

INSERT INTO SNIPER VALUES (1, 'Russian-Svd', 4);

SELECT * FROM PISTOLA
SELECT * FROM METRALLETA
SELECT * FROM SNIPER

Select p.ID, p.MODELO_PISTOLA, a.DANHO, a.TAMANHO, a.ALCANCE, a.CARGADOR_BALAS, a.MIRA 
from PISTOLA p, ARMA a
where P.ID_ARMA = a.ID

Select m.ID, m.MODELO_METRALLETA, a.DANHO, a.TAMANHO, a.ALCANCE, a.CARGADOR_BALAS, a.MIRA
from METRALLETA m, ARMA a
where m.ID_ARMA = a.ID

Select s.ID, s.MODELO_SNIPER,a.DANHO, a.TAMANHO, a.ALCANCE, a.CARGADOR_BALAS, a.MIRA
from SNIPER s, ARMA a
where s.ID_ARMA = a.ID

